export const volunteers = [
  {
    id: "1",
    name: "María González",
    email: "maria.gonzalez@email.com",
    phone: "+56 9 1234 5678",
    region: "Región Metropolitana",
    city: "Santiago",
    skills: ["Primeros Auxilios", "Comunicación", "Logística"],
    campaigns: ["Teletón 2024", "Teletón 2023"],
    availability: "Fines de semana",
    volunteerType: "Presencial",
    status: "Activo",
    notes: "Voluntaria muy comprometida",
    joinDate: "2022-03-15",
  },
  {
    id: "2",
    name: "Carlos Rodríguez",
    email: "carlos.rodriguez@email.com",
    phone: "+56 9 8765 4321",
    region: "Valparaíso",
    city: "Viña del Mar",
    skills: ["Tecnología", "Redes Sociales"],
    campaigns: ["Teletón 2024"],
    availability: "Flexible",
    volunteerType: "Virtual",
    status: "Activo",
    notes: "",
    joinDate: "2024-01-10",
  },
  {
    id: "3",
    name: "Ana Martínez",
    email: "ana.martinez@email.com",
    phone: "+56 9 5555 1234",
    region: "Biobío",
    city: "Concepción",
    skills: ["Educación", "Animación", "Primeros Auxilios"],
    campaigns: ["Teletón 2024", "Teletón 2023", "Teletón 2022"],
    availability: "Tardes",
    volunteerType: "Presencial",
    status: "Activo",
    notes: "Profesora de educación básica",
    joinDate: "2021-08-20",
  },
  {
    id: "4",
    name: "Pedro Silva",
    email: "pedro.silva@email.com",
    phone: "+56 9 9999 8888",
    region: "Araucanía",
    city: "Temuco",
    skills: ["Transporte", "Logística"],
    campaigns: ["Teletón 2024"],
    availability: "Mañanas",
    volunteerType: "Presencial",
    status: "Pendiente",
    notes: "Conductor profesional",
    joinDate: "2024-06-01",
  },
  {
    id: "5",
    name: "Sofía Hernández",
    email: "sofia.hernandez@email.com",
    phone: "+56 9 7777 6666",
    region: "Los Lagos",
    city: "Puerto Montt",
    skills: ["Comunicación", "Fotografía", "Redes Sociales"],
    campaigns: ["Teletón 2024", "Teletón 2023"],
    availability: "Fines de semana",
    volunteerType: "Híbrido",
    status: "Activo",
    notes: "Periodista freelance",
    joinDate: "2023-02-28",
  },
  {
    id: "6",
    name: "Diego Fuentes",
    email: "diego.fuentes@email.com",
    phone: "+56 9 4444 3333",
    region: "Región Metropolitana",
    city: "Maipú",
    skills: ["Tecnología", "Soporte Técnico"],
    campaigns: ["Teletón 2024"],
    availability: "Noches",
    volunteerType: "Virtual",
    status: "Activo",
    notes: "Ingeniero en informática",
    joinDate: "2024-03-15",
  },
  {
    id: "7",
    name: "Valentina Rojas",
    email: "valentina.rojas@email.com",
    phone: "+56 9 2222 1111",
    region: "Coquimbo",
    city: "La Serena",
    skills: ["Primeros Auxilios", "Enfermería"],
    campaigns: ["Teletón 2024", "Teletón 2023", "Teletón 2022", "Teletón 2021"],
    availability: "Flexible",
    volunteerType: "Presencial",
    status: "Activo",
    notes: "Enfermera titulada",
    joinDate: "2020-11-10",
  },
  {
    id: "8",
    name: "Matías López",
    email: "matias.lopez@email.com",
    phone: "+56 9 6666 5555",
    region: "Maule",
    city: "Talca",
    skills: ["Animación", "Música"],
    campaigns: ["Teletón 2024"],
    availability: "Fines de semana",
    volunteerType: "Presencial",
    status: "Inactivo",
    notes: "Estudiante de música",
    joinDate: "2024-05-20",
  },
]

export const regions = [
  "Arica y Parinacota",
  "Tarapacá",
  "Antofagasta",
  "Atacama",
  "Coquimbo",
  "Valparaíso",
  "Región Metropolitana",
  "O'Higgins",
  "Maule",
  "Ñuble",
  "Biobío",
  "Araucanía",
  "Los Ríos",
  "Los Lagos",
  "Aysén",
  "Magallanes",
]

export const skills = [
  "Primeros Auxilios",
  "Comunicación",
  "Logística",
  "Tecnología",
  "Redes Sociales",
  "Educación",
  "Animación",
  "Transporte",
  "Fotografía",
  "Soporte Técnico",
  "Enfermería",
  "Música",
]

export const campaigns = ["Teletón 2024", "Teletón 2023", "Teletón 2022", "Teletón 2021"]

export const availabilityOptions = ["Mañanas", "Tardes", "Noches", "Fines de semana", "Flexible"]

export const volunteerTypes = ["Presencial", "Virtual", "Híbrido"]

export const logs = [
  {
    id: "1",
    timestamp: "2024-11-28 14:32:15",
    type: "Sincronización",
    message: "Sincronización de datos completada exitosamente",
    status: "success",
  },
  {
    id: "2",
    timestamp: "2024-11-28 14:30:00",
    type: "Comunicación",
    message: "Envío de correos masivos: 150 voluntarios notificados",
    status: "success",
  },
  {
    id: "3",
    timestamp: "2024-11-28 13:45:22",
    type: "Error",
    message: "Error al conectar con API externa - Reintentando...",
    status: "error",
  },
  {
    id: "4",
    timestamp: "2024-11-28 12:00:00",
    type: "Segmentación",
    message: "Nueva segmentación creada: Voluntarios RM - Presencial",
    status: "info",
  },
  {
    id: "5",
    timestamp: "2024-11-28 10:15:30",
    type: "Importación",
    message: "Importación de 45 nuevos voluntarios completada",
    status: "success",
  },
  {
    id: "6",
    timestamp: "2024-11-27 16:20:00",
    type: "Sincronización",
    message: "Actualización de datos de campañas",
    status: "success",
  },
  {
    id: "7",
    timestamp: "2024-11-27 14:00:00",
    type: "Warning",
    message: "5 registros duplicados detectados - Revisión pendiente",
    status: "warning",
  },
]

export const regionStats = [
  { region: "RM", volunteers: 1250, percentage: 35 },
  { region: "Valparaíso", volunteers: 420, percentage: 12 },
  { region: "Biobío", volunteers: 380, percentage: 11 },
  { region: "Araucanía", volunteers: 290, percentage: 8 },
  { region: "Los Lagos", volunteers: 250, percentage: 7 },
  { region: "Coquimbo", volunteers: 200, percentage: 6 },
  { region: "Maule", volunteers: 180, percentage: 5 },
  { region: "Otras", volunteers: 580, percentage: 16 },
]

export const skillsStats = [
  { skill: "Primeros Auxilios", count: 890 },
  { skill: "Comunicación", count: 720 },
  { skill: "Logística", count: 650 },
  { skill: "Tecnología", count: 580 },
  { skill: "Redes Sociales", count: 520 },
  { skill: "Educación", count: 450 },
  { skill: "Animación", count: 380 },
  { skill: "Transporte", count: 320 },
]

export const campaignParticipation = [
  { campaign: "2021", volunteers: 2800 },
  { campaign: "2022", volunteers: 3200 },
  { campaign: "2023", volunteers: 3450 },
  { campaign: "2024", volunteers: 3550 },
]
